"use strict";

/**
 * Local WhatsApp sidecar (docs/archive/UI_UX_AUDIT.md Phase 16).
 *
 * Owned and spawned by the Python backend (channels/whatsapp_bridge_process.py),
 * never run standalone in production. Talks to WhatsApp via Baileys (an
 * unofficial WhatsApp Web client, QR-linked - no Meta account, no public
 * webhook) and exposes three loopback-only HTTP routes so the Python side
 * never has to touch Baileys' raw protocol objects:
 *
 *   GET  /health           -> { ok, linked }
 *   GET  /updates?offset=N -> { messages: [...], next_offset }  (mirrors Telegram's getUpdates)
 *   POST /send { chat_id, text } -> { id, status }
 *
 * Every request must carry `X-Bridge-Secret: <WHATSAPP_BRIDGE_SECRET>` - a
 * fresh secret generated by the Python parent at spawn time and handed to
 * this process by env var only (never a CLI arg, never logged), so nothing
 * else on the machine can talk to this bridge without also being able to
 * read the Python parent's own environment or its gitignored state file.
 *
 * On first run (no saved session in WHATSAPP_AUTH_DIR), Baileys emits a QR
 * code - printed straight to stdout via qrcode-terminal, which the parent's
 * log redirection already captures (`ybm logs whatsapp --follow` is how a
 * user watches for and scans it). No QR-serving HTTP route needed.
 */

// ESM, not CommonJS: @whiskeysockets/baileys is `"type": "module"` and
// `require()`-ing it throws ERR_REQUIRE_ESM on Node < 22.12 (where
// require(esm) is still behind a flag). `node --check` only parses syntax
// and never resolves imports, so that failure is invisible to a syntax
// check - `npm run check` in this package actually loads the module graph.
import http from "node:http";
import { URL, pathToFileURL } from "node:url";
import pino from "pino";
import qrcodeTerminal from "qrcode-terminal";
import makeWASocket, {
  useMultiFileAuthState,
  fetchLatestBaileysVersion,
  DisconnectReason,
  isJidGroup,
  isJidBroadcast,
  isJidNewsletter,
  isLidUser,
} from "@whiskeysockets/baileys";

const PORT = Number(process.env.WHATSAPP_BRIDGE_PORT || 8091);
const SECRET = process.env.WHATSAPP_BRIDGE_SECRET || "";
const AUTH_DIR = process.env.WHATSAPP_AUTH_DIR || ".whatsapp_auth";
// Bounds the in-memory update buffer so a bridge nobody is polling doesn't
// grow without limit - a documented v1 limitation, not a persistent queue
// (see docs/archive/UI_UX_AUDIT.md Phase 16's write-up on this exact tradeoff).
const MAX_BUFFERED_MESSAGES = 500;

// The missing-secret guard lives in main(), not here at module scope, so
// importing this file to verify its imports resolve doesn't exit(1).

let linked = false;
let sock = null;
let nextId = 1;
const buffer = []; // [{ offset, id, from, chat_id, text, timestamp }]

// Bounded, backing-off reconnect: an immediate, uncapped retry loop against
// WhatsApp's own servers is close to the worst thing this bridge could do
// to the linked account's ban risk - the exact concern that ruled out
// linking a primary number in the first place. Resets to the base delay
// once a connection actually opens.
const RECONNECT_BASE_DELAY_MS = 2000;
const RECONNECT_MAX_DELAY_MS = 60000;
let reconnectDelayMs = RECONNECT_BASE_DELAY_MS;

function pushMessage(message) {
  const entry = { offset: nextId++, ...message };
  buffer.push(entry);
  while (buffer.length > MAX_BUFFERED_MESSAGES) buffer.shift();
}

function extractText(message, depth = 0) {
  if (!message || depth > 3) return "";
  // Disappearing messages (on by default for new chats on many accounts)
  // and view-once messages wrap the real payload one or more levels deep.
  // Without unwrapping, every message from such a chat extracts as "" and
  // is silently dropped - the channel would look completely dead with no
  // error anywhere. Depth-capped so a malformed/hostile nesting chain
  // can't spin here.
  const wrapped =
    message.ephemeralMessage?.message ||
    message.viewOnceMessage?.message ||
    message.viewOnceMessageV2?.message ||
    message.viewOnceMessageV2Extension?.message ||
    message.documentWithCaptionMessage?.message;
  if (wrapped) return extractText(wrapped, depth + 1);
  return (
    message.conversation ||
    message.extendedTextMessage?.text ||
    message.imageMessage?.caption ||
    message.videoMessage?.caption ||
    message.documentMessage?.caption ||
    ""
  );
}

async function startBaileys() {
  const { state, saveCreds } = await useMultiFileAuthState(AUTH_DIR);
  const { version } = await fetchLatestBaileysVersion();

  const thisSock = makeWASocket({
    version,
    auth: state,
    logger: pino({ level: "silent" }),
  });
  sock = thisSock;

  thisSock.ev.on("creds.update", saveCreds);

  thisSock.ev.on("connection.update", (update) => {
    // A superseded socket can still emit after we've moved on to its
    // replacement; without this guard each stale 'close' would schedule
    // its own reconnect, so one dropped connection can fan out into
    // several parallel reconnect chains all sharing one backoff counter.
    if (sock !== thisSock) return;
    const { connection, lastDisconnect, qr } = update;
    if (qr) {
      console.log("Scan this QR code with WhatsApp (Linked devices -> Link a device):");
      qrcodeTerminal.generate(qr, { small: true });
      // The ASCII art above is Unicode half-block characters - `ybm logs
      // whatsapp` reads this log back through PowerShell, whose default
      // console encoding on Windows (especially 5.1) can mangle those into
      // an unscannable mess with no error, no fallback, and no other way
      // to link an account. The raw payload printed as plain ASCII text is
      // encoding-proof: paste it into any online QR generator (e.g.
      // https://www.qr-code-generator.com) if the art above doesn't
      // render as a clean grid. Baileys reissues a fresh QR roughly every
      // 20-60s until scanned, so `ybm logs whatsapp -Follow` will show a
      // current one shortly after being started even if the very first
      // one is missed.
      console.log(`Raw QR payload (paste into a QR generator if the code above looks garbled):\n${qr}`);
    }
    if (connection === "open") {
      linked = true;
      reconnectDelayMs = RECONNECT_BASE_DELAY_MS;
      console.log("WhatsApp bridge connected.");
    }
    if (connection === "close") {
      linked = false;
      const statusCode = lastDisconnect?.error?.output?.statusCode;
      const loggedOut = statusCode === DisconnectReason.loggedOut;
      if (loggedOut) {
        console.error("WhatsApp session was logged out - delete the auth directory and restart to re-link.");
        return;
      }
      const delay = reconnectDelayMs;
      reconnectDelayMs = Math.min(reconnectDelayMs * 2, RECONNECT_MAX_DELAY_MS);
      console.warn(`WhatsApp connection closed - reconnecting in ${delay}ms.`);
      setTimeout(() => {
        startBaileys().catch((exc) => console.error("reconnect failed:", exc));
      }, delay);
    }
  });

  thisSock.ev.on("messages.upsert", ({ messages, type }) => {
    if (type !== "notify") return;
    for (const msg of messages) {
      if (msg.key.fromMe) continue;
      const jid = msg.key.remoteJid || "";
      // Group chats, Status broadcasts, and newsletters are not supported
      // in v1 - allowed_numbers is an individual-number allowlist with
      // nowhere for those ids to match, so they would only ever be
      // denied-and-audited noise; drop them at the source. Using Baileys'
      // own predicates rather than matching "@g.us" by hand keeps this
      // correct if it ever adds or renames a JID server.
      if (isJidGroup(jid) || isJidBroadcast(jid) || isJidNewsletter(jid)) continue;
      const text = extractText(msg.message).trim();
      if (!text) continue;
      pushMessage({
        id: msg.key.id,
        from: jid,
        chat_id: jid,
        text,
        timestamp: Number(msg.messageTimestamp || 0) * 1000,
        // WhatsApp's privacy-preserving "LID" addressing (@lid, distinct
        // from the traditional <number>@s.whatsapp.net) sends an opaque
        // id instead of the phone number - there is no lookup exposed
        // here to resolve it back to a real number, so it can never match
        // channels.whatsapp.allowed_numbers. Passed through as a labeled
        // fact rather than silently denied-and-unexplained.
        is_lid: isLidUser(jid),
      });
    }
  });
}

function checkSecret(req) {
  return req.headers["x-bridge-secret"] === SECRET;
}

function sendJson(res, status, body) {
  const payload = JSON.stringify(body);
  res.writeHead(status, { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(payload) });
  res.end(payload);
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = "";
    req.on("data", (chunk) => {
      data += chunk;
      if (data.length > 1_000_000) {
        reject(new Error("request body too large"));
        req.destroy();
      }
    });
    req.on("end", () => resolve(data));
    req.on("error", reject);
  });
}

const server = http.createServer(async (req, res) => {
  if (!checkSecret(req)) {
    sendJson(res, 401, { error: "unauthorized" });
    return;
  }
  const url = new URL(req.url, "http://127.0.0.1");

  try {
    if (req.method === "GET" && url.pathname === "/health") {
      sendJson(res, 200, { ok: true, linked });
      return;
    }

    if (req.method === "GET" && url.pathname === "/updates") {
      const offset = Number(url.searchParams.get("offset") || 0);
      const messages = buffer.filter((entry) => entry.offset > offset);
      const nextOffset = messages.length > 0 ? messages[messages.length - 1].offset : offset;
      sendJson(res, 200, { messages, next_offset: nextOffset });
      return;
    }

    if (req.method === "POST" && url.pathname === "/send") {
      if (!linked || !sock) {
        sendJson(res, 503, { error: "whatsapp_not_linked" });
        return;
      }
      const body = JSON.parse((await readBody(req)) || "{}");
      const chatId = String(body.chat_id || "");
      const text = String(body.text || "");
      if (!chatId || !text) {
        sendJson(res, 400, { error: "chat_id and text are required" });
        return;
      }
      const result = await sock.sendMessage(chatId, { text });
      sendJson(res, 200, { id: result?.key?.id || null, status: "sent" });
      return;
    }

    sendJson(res, 404, { error: "not_found" });
  } catch (exc) {
    console.error("request failed:", exc);
    sendJson(res, 500, { error: String(exc && exc.message ? exc.message : exc) });
  }
});

server.on("error", (exc) => {
  // Without this, EADDRINUSE (or any other listen failure) is an unhandled
  // 'error' event - node exits immediately with no message, and the Python
  // parent's health check just burns its full timeout before reporting a
  // generic "did not become healthy".
  console.error(`failed to listen on 127.0.0.1:${PORT}:`, exc.message);
  process.exit(1);
});

function main() {
  if (!SECRET) {
    console.error("WHATSAPP_BRIDGE_SECRET is not set - refusing to start with no request authentication.");
    process.exit(1);
  }
  server.listen(PORT, "127.0.0.1", () => {
    console.log(`WhatsApp bridge listening on 127.0.0.1:${PORT}`);
  });

  startBaileys().catch((exc) => {
    console.error("failed to start WhatsApp connection:", exc);
    process.exit(1);
  });

  process.on("SIGTERM", () => process.exit(0));
  process.on("SIGINT", () => process.exit(0));
}

// Only bind the port and dial WhatsApp when actually run as the entry
// point. Importing this file (npm run check) then verifies the whole
// import graph resolves - the check that would have caught this package
// being CommonJS while Baileys is ESM-only - without opening a socket or
// touching the linked account.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
